### ISSUE TITLE
customizing dashboard views

### ISSUE THREAD

**Issue by GrilloPress** [FlyoverWorks/storytime#73]
Love the product but to make use of it in a production tool that I'd hand to a client I will need to customize the way the dashboard looks.

I could fork/hack on your Engine and edit it there or through the downloaded gem or maybe try to write in overrides into my app.

I was wondering what is the preferred way you guys do it? Is there a way to pull in the dashboard views into my app? And is there a way to pull in your dashboard scss?

**Comment by bcroesch** [comment]
@GrilloPress - glad to hear you're interested in using Storytime. Couple of thoughts:

-Overriding the views would be pretty easy. E.g. to override the post#edit action, you could just stick a file in your host app at: ```app/views/storytime/dashboard/posts/edit.html.erb```. You could do that with any view in the dashboard pretty easily. If necessary, we could add something to our install generator to copy over dashboard views.

-You should be able to override styles in a similar manner. E.g. if you want to override admin styles, you could put a file in your host app at: ```app/assets/stylesheets/storytime/admin.css.scss``` and do whatever you want in there. If you want to just tweak minor things, you could copy the source for that file into your host app and make changes.

In order to make the stylesheet override work in development, you'll probably need to have a local copy of the storytime source:
```
cd /wherever/you/want/storytime/source
git clone git@github.com:FlyoverWorks/storytime.git
bundle config local.storytime /wherever/you/want/storytime/source
```

I think going with the override route would be much easier/cleaner than forking and changing. Plus, it will be much easier to stay up to date with future releases.

It's also worth noting that we're actively working on a 2.0 release right now. One of the major features is going to be a major overhaul of the dashboard UI. Going to be professionally designed and mobile responsive -- should turn out great.


If you run into any snags with the overrides, feel free to respond here and I'm happy to help out.

**Comment by GrilloPress** [comment]
thanks for the advice @bcroesch I think i'll go the override route. It did always seem the most sensible approach.

Once again. Lovely product. Really looking forward to seeing it shape up. 

I'd love an install generator for the dashboard views and scss. It really aligns with my philosophy of a great Engine. For those learning and using your product for the first few times, let them see it in their app before their eyes. When they get a good grounding in your code and flow, let them keep it out of the app and let them declutter. 

That said, i'm just one guy so on the product roadmap I doubt there is much urgent need there :)  and the dashboard redesign I think is a good strategic move for adoption.

I look forward to seeing 2.0

**Comment by bcroesch** [comment]
Agree that an install generator is a good idea. Something similar to Devise's ```rails generate devise:views``` would make a lot of sense. We'll stick it on the 2.0 roadmap.

Thanks again for checking out Storytime and ping us with any questions/issues!
